name: Fairy

on:
  schedule:
    - cron: '25 18 * * *' # tous les jours à 22h25 heure Réunion
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run commit script
        run: |
          git config --global user.name ${GITHUB_ACTOR}
          git config --global user.email ${{ secrets.USER_EMAIL }}
          git commit --allow-empty -m "Plant grass: `date +'%Y-%m-%d %H:%M:%S'`" 
          git push origin master
