name: autocontrib

on:
  schedule:
    - cron: '0 12 * * *' # tous les jours à 16h heure Réunion (UTC+4)
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Git auth
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ secrets.USER_EMAIL }}"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}

      - name: Run commit script
        run: |
          git commit --allow-empty -m "Plant grass: `date +'%Y-%m-%d %H:%M:%S'`"
          git push origin master
